name: Install virtual audio device
description: Install Scream virtual audio device

runs:
  using: composite
  steps:
    - name: Install Scream virtual audio device
      run: |
        Start-Service audio*
        Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
        Expand-Archive -Path C:\Scream3.6.zip -DestinationPath C:\Scream
        $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
        $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
        $store.Open("ReadWrite")
        $store.Add($cert)
        $store.Close()
        cd C:\Scream\Install\driver
        C:\Scream\Install\helpers\devcon install Scream.inf *Scream
        Get-CimInstance Win32_SoundDevice | fl * # Print audio device info.
      shell: powershell
