name: Build & Test
description: Build solution and run all tests

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Build solution
      run: dotnet build Geisha.sln --configuration Debug
      shell: powershell

    - name: Install Scream virtual audio device
      run: |
        Start-Service audio*
        Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
        Expand-Archive -Path C:\Scream3.6.zip -DestinationPath C:\Scream
        $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
        $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
        $store.Open("ReadWrite")
        $store.Add($cert)
        $store.Close()
        cd C:\Scream\Install\driver
        C:\Scream\Install\helpers\devcon install Scream.inf *Scream
        Get-CimInstance Win32_SoundDevice | fl * # Print audio device info.
      shell: powershell

    - name: Execute tests
      run: dotnet test Geisha.sln --configuration Debug --no-build --logger "trx;LogFileName=test-results.trx"
      shell: powershell

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results
        path: test/**/test-results.trx
        reporter: dotnet-trx
