<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Description>$(Geisha_DescriptionPrefix) This package provides implementation of windowing backend for Windows using WinForms and Win32.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpDX.Desktop" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Geisha.Engine\Geisha.Engine.csproj" />
  </ItemGroup>

</Project>
